/**
 * Two-pass Style Dictionary build:
 *   Pass 1 — light mode:  outputs tokens.css, tokens.js, tokens.d.ts, tokens.json, _tokens.scss
 *   Pass 2 — dark mode:   outputs tokens.dark.css
 *
 * Style Dictionary resolves "{color.blue.500}" references at build time,
 * so CSS custom properties contain final computed values, not references.
 *
 * NOTE on 'typescript/esm-declarations':
 * Style Dictionary v4 removed several built-in formats including the TS
 * declarations format. We register it as a custom format below.
 * A "format" in Style Dictionary is just a function that receives the token
 * dictionary and returns a string — we write that string to the output file.
 */
import StyleDictionary from 'style-dictionary';

// ─── REGISTER CUSTOM FORMAT: typescript/esm-declarations ─────────────────────
//
// This format generates a .d.ts file that re-exports every token as a typed
// string constant. Consumers get autocomplete on token names in TypeScript.
//
// Example output:
//   export declare const StampColorBrandPrimary: string;
//   export declare const StampButtonRadius: string;
//
// How it works:
//   dictionary.allTokens — flat list of every resolved token
//   token.name           — the camelCase token name (Style Dictionary generates
//                          this from the nested JSON path: color.brand.primary
//                          → 'StampColorBrandPrimary' after the prefix)
StyleDictionary.registerFormat({
  name: 'typescript/esm-declarations',
  format: ({ dictionary }) => {
    const declarations = dictionary.allTokens
      .map(token => {
        // Convert the token name to a valid JS identifier:
        // "stamp-color-brand-primary" → "StampColorBrandPrimary"
        const varName = token.name
          .split('-')
          .map(part => part.charAt(0).toUpperCase() + part.slice(1))
          .join('');
        return `export declare const ${varName}: string;`;
      })
      .join('\n');
    return `// Auto-generated by @stamp-ds/tokens — do not edit manually\n${declarations}\n`;
  },
});

const PLATFORMS = {
  css: {
    transformGroup: 'css',
    prefix: 'stamp',
    buildPath: 'dist/css/',
    files: [{ destination: 'tokens.css', format: 'css/variables' }],
  },
  js: {
    transformGroup: 'js',
    buildPath: 'dist/js/',
    files: [
      { destination: 'tokens.js',   format: 'javascript/esm' },
      { destination: 'tokens.d.ts', format: 'typescript/esm-declarations' },
    ],
  },
  json: {
    transformGroup: 'js',
    buildPath: 'dist/json/',
    files: [{ destination: 'tokens.json', format: 'json/nested' }],
  },
  scss: {
    transformGroup: 'scss',
    buildPath: 'dist/scss/',
    files: [{ destination: '_tokens.scss', format: 'scss/variables' }],
  },
};

// Pass 1: light mode — all platforms
const light = new StyleDictionary({
  source: [
    'src/primitive/**/*.json',
    'src/semantic/color.light.json',
    'src/semantic/typography.json',
    'src/semantic/spacing.json',
    'src/component/**/*.json',
  ],
  platforms: PLATFORMS,
});
await light.buildAllPlatforms();
console.log('✓ Light mode tokens built');

// Pass 2: dark mode — CSS only, separate output file
const dark = new StyleDictionary({
  source: [
    'src/primitive/**/*.json',
    'src/semantic/color.dark.json',
    'src/semantic/typography.json',
    'src/semantic/spacing.json',
    'src/component/**/*.json',
  ],
  platforms: {
    css: {
      transformGroup: 'css',
      prefix: 'stamp',
      buildPath: 'dist/css/',
      files: [{ destination: 'tokens.dark.css', format: 'css/variables' }],
    },
  },
});
await dark.buildAllPlatforms();
console.log('✓ Dark mode tokens built');
